# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sidhant
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: cf-email
# "service" is the name of this project. This will also be added to your AWS resource names.
service: cf-email

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1
  stage: dev
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
      Resource: "*"  

functions:
  sendEmail:
    handler: src/sendEmail.handler
    events:
      - httpApi:
          path: /send-email
          method: post
